(() => {
'use strict';
const PROTOCOL='2025-06-18'; let id=0;
const config=()=>({enabled:localStorage.getItem('mcp_enabled')==='true',url:(localStorage.getItem('mcp_url')||'').trim(),token:(localStorage.getItem('mcp_token')||'').trim(),allowRead:localStorage.getItem('mcp_allow_read')!=='false',allowWrite:localStorage.getItem('mcp_allow_write')==='true'});
const isWriteTool=name=>/(?:^|[_./-])(write|create|update|delete|remove|send|reply|save|set|put|patch|publish|submit|archive|restore)(?:$|[_./-])/i.test(String(name||''));
const parseSse=text=>{const rows=String(text||'').split(/\r?\n/).filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trim()).filter(x=>x&&x!=='[DONE]');if(!rows.length)throw new Error('MCP 服务返回了无法识别的 SSE 响应');return JSON.parse(rows.at(-1));};
async function rpc(method,params={},override={}){const c={...config(),...override};if(!c.url)throw new Error('未配置 MCP 服务地址');const headers={'Content-Type':'application/json','Accept':'application/json, text/event-stream'};if(c.token)headers.Authorization=`Bearer ${c.token}`;if(c.sessionId)headers['Mcp-Session-Id']=c.sessionId;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const res=await fetch(c.url,{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:++id,method,params}),signal:controller.signal});const sessionId=res.headers.get('Mcp-Session-Id')||res.headers.get('mcp-session-id')||c.sessionId||'';const text=await res.text();if(!res.ok)throw new Error(`HTTP ${res.status}${text?`：${text.slice(0,500)}`:''}`);let payload=null;if(text.trim())payload=(res.headers.get('content-type')||'').includes('text/event-stream')||text.trimStart().startsWith('data:')?parseSse(text):JSON.parse(text);if(payload?.error)throw new Error(payload.error.message||`MCP 错误 ${payload.error.code||''}`.trim());return{result:payload?.result??payload,sessionId};}catch(e){if(e?.name==='AbortError')throw new Error('MCP 请求超过 30 秒，已停止');if(navigator.onLine===false)throw new Error('当前设备已断网');throw e;}finally{clearTimeout(timer);}}
async function initialize(override={}){const first=await rpc('initialize',{protocolVersion:PROTOCOL,capabilities:{},clientInfo:{name:'Jingxu',version:'1.0.0'}},override);try{await rpc('notifications/initialized',{}, {...override,sessionId:first.sessionId});}catch(_){}return first;}
async function listTools(override={}){const init=await initialize(override),listed=await rpc('tools/list',{}, {...override,sessionId:init.sessionId});return{tools:Array.isArray(listed.result?.tools)?listed.result.tools:[],serverInfo:init.result?.serverInfo||null,capabilities:init.result?.capabilities||{},sessionId:listed.sessionId||init.sessionId||''};}
async function callTool(name,args={},override={}){const c={...config(),...override};if(!c.enabled&&!override.ignoreEnabled)throw new Error('MCP 尚未启用');const write=isWriteTool(name);if(write&&!c.allowWrite)throw new Error('当前设置不允许 MCP 写入');if(!write&&!c.allowRead)throw new Error('当前设置不允许 MCP 读取');const init=await initialize(c);return(await rpc('tools/call',{name,arguments:args},{...c,sessionId:init.sessionId})).result;}
async function testConnection({url,token=''}){const r=await listTools({url,token,enabled:true,allowRead:true,allowWrite:false});return{ok:true,toolCount:r.tools.length,tools:r.tools,serverName:r.serverInfo?.name||'',serverVersion:r.serverInfo?.version||''};}
window.MCPClient={getConfig:config,initialize,listTools,callTool,testConnection,isWriteTool};
})();
