from pathlib import Path

index = Path('index.html')
main = Path('main.js')

html = index.read_text(encoding='utf-8')
marker = '''                            </div>\n                        </div>\n                    </div>\n                    <button class="btn-primary" id="save-api-btn"'''
start = html.find('<label style="margin:0; font-weight: 600;">记忆专属 API (可选)</label>')
pos = html.find(marker, start)
if start < 0 or pos < 0:
    raise SystemExit('Could not locate API settings insertion point')

mcp_block = '''                            </div>\n                        </div>\n                        <div class="form-group" style="margin-top: 20px; border-top: 1px solid #eaeaea; padding-top: 20px;">\n                            <div class="flex-between" style="margin-bottom: 15px;">\n                                <label style="margin:0; font-weight: 600;">MCP</label>\n                                <label class="switch memory-switch" style="transform: scale(0.8); transform-origin: right center;"><input type="checkbox" id="mcp-enabled-switch" onchange="document.getElementById('mcp-fields').style.display=this.checked?'block':'none'"><span class="slider"></span></label>\n                            </div>\n                            <div style="font-size: 11px; color: #888; margin-bottom: 15px; line-height: 1.6;">填写支持 Streamable HTTP 的 MCP 接口。地址默认留空，连接令牌可选。</div>\n                            <div id="mcp-fields" style="display: none;">\n                                <div class="form-group"><label>MCP 服务地址</label><input type="url" id="mcp-url" placeholder="https://example.com/api/mcp" autocomplete="off"></div>\n                                <div class="form-group"><label>连接令牌（可选）</label><input type="password" id="mcp-token" placeholder="Bearer Token" autocomplete="off" onfocus="this.type='text'" onblur="this.type='password'"></div>\n                                <div class="form-group" style="margin-bottom: 12px;">\n                                    <div class="flex-between" style="padding: 10px 0;"><span style="font-size: 14px; color: #444;">允许读取</span><label class="switch memory-switch" style="transform: scale(0.8); transform-origin: right center;"><input type="checkbox" id="mcp-allow-read-switch" checked><span class="slider"></span></label></div>\n                                    <div class="flex-between" style="padding: 10px 0; border-top: 1px solid #f0f0f0;"><span style="font-size: 14px; color: #444;">允许写入</span><label class="switch memory-switch" style="transform: scale(0.8); transform-origin: right center;"><input type="checkbox" id="mcp-allow-write-switch"><span class="slider"></span></label></div>\n                                </div>\n                                <button type="button" id="test-mcp-btn" style="width:100%;border:1px solid #d8d8d8;background:#fff;color:#444;border-radius:14px;padding:13px 16px;font-size:14px;cursor:pointer;">测试连接</button>\n                                <div id="mcp-test-status" style="font-size:11px;color:#888;margin-top:10px;line-height:1.5;min-height:16px;"></div>\n                            </div>\n                        </div>\n                    </div>\n                    <button class="btn-primary" id="save-api-btn"'''

html = html[:pos] + mcp_block + html[pos + len(marker) - len('                    <button class="btn-primary" id="save-api-btn"'):]
html = html.replace('    <script src="main.js"></script>', '    <script src="mcpClient.js"></script>\n    <script src="main.js"></script>', 1)
index.write_text(html, encoding='utf-8')

js = main.read_text(encoding='utf-8')
open_anchor = """            const savedImgModel = localStorage.getItem('image_api_model') || '';\n            const imgModelSelect = $('image-api-model');\n            if (imgModelSelect) {\n                if (savedImgModel && !Array.from(imgModelSelect.options).some(opt => opt.value === savedImgModel)) {\n                    imgModelSelect.add(new Option(savedImgModel, savedImgModel));\n                }\n                imgModelSelect.value = savedImgModel;\n            }\n\n            renderApiPresets();"""
if open_anchor not in js:
    raise SystemExit('Could not locate API open handler')
js = js.replace(open_anchor, open_anchor.replace('\n\n            renderApiPresets();', """\n\n            const mcpEnabled = localStorage.getItem('mcp_enabled') === 'true';\n            if ($('mcp-enabled-switch')) $('mcp-enabled-switch').checked = mcpEnabled;\n            if ($('mcp-fields')) $('mcp-fields').style.display = mcpEnabled ? 'block' : 'none';\n            if ($('mcp-url')) $('mcp-url').value = localStorage.getItem('mcp_url') || '';\n            if ($('mcp-token')) $('mcp-token').value = localStorage.getItem('mcp_token') || '';\n            if ($('mcp-allow-read-switch')) $('mcp-allow-read-switch').checked = localStorage.getItem('mcp_allow_read') !== 'false';\n            if ($('mcp-allow-write-switch')) $('mcp-allow-write-switch').checked = localStorage.getItem('mcp_allow_write') === 'true';\n            if ($('mcp-test-status')) $('mcp-test-status').textContent = '';\n\n            renderApiPresets();"""), 1)

save_anchor = "        on($('save-api-btn'), 'click', () => { "
test_handler = """        if ($('test-mcp-btn')) {\n            on($('test-mcp-btn'), 'click', async () => {\n                const url = $('mcp-url')?.value.trim() || '';\n                const token = $('mcp-token')?.value.trim() || '';\n                const status = $('mcp-test-status');\n                const btn = $('test-mcp-btn');\n                if (!url) { status.textContent = '请先填写 MCP 服务地址'; status.style.color = '#c0392b'; return; }\n                try { new URL(url); } catch (_) { status.textContent = '服务地址格式不正确'; status.style.color = '#c0392b'; return; }\n                const oldText = btn.textContent; btn.disabled = true; btn.textContent = '连接中…';\n                status.textContent = '正在初始化 MCP 连接…'; status.style.color = '#888';\n                try {\n                    const result = await window.MCPClient.testConnection({ url, token });\n                    status.textContent = `连接成功 · 发现 ${result.toolCount} 个工具${result.serverName ? ` · ${result.serverName}` : ''}`;\n                    status.style.color = '#2e7d32';\n                } catch (error) { status.textContent = `连接失败：${error.message || error}`; status.style.color = '#c0392b'; }\n                finally { btn.disabled = false; btn.textContent = oldText; }\n            });\n        }\n\n"""
if save_anchor not in js:
    raise SystemExit('Could not locate API save handler')
js = js.replace(save_anchor, test_handler + save_anchor, 1)

save_mem = """            const memApiSwitch = $('memory-api-switch');\n            if (memApiSwitch) {\n                localStorage.setItem('memory_api_enabled', memApiSwitch.checked ? 'true' : 'false');\n                ['url','key','model'].forEach(k => {\n                    const el = $(`memory-api-${k}`);\n                    if (el) localStorage.setItem(`memory_api_${k}`, el.value.trim());\n                });\n            }\n            \n            const select = $('api-preset-select');"""
save_mcp = """            const memApiSwitch = $('memory-api-switch');\n            if (memApiSwitch) {\n                localStorage.setItem('memory_api_enabled', memApiSwitch.checked ? 'true' : 'false');\n                ['url','key','model'].forEach(k => {\n                    const el = $(`memory-api-${k}`);\n                    if (el) localStorage.setItem(`memory_api_${k}`, el.value.trim());\n                });\n            }\n\n            const mcpEnabled = Boolean($('mcp-enabled-switch')?.checked);\n            const mcpUrl = $('mcp-url')?.value.trim() || '';\n            if (mcpEnabled && !mcpUrl) { showAlert('启用 MCP 前请填写服务地址'); return; }\n            if (mcpUrl) { try { new URL(mcpUrl); } catch (_) { showAlert('MCP 服务地址格式不正确'); return; } }\n            localStorage.setItem('mcp_enabled', mcpEnabled ? 'true' : 'false');\n            localStorage.setItem('mcp_url', mcpUrl);\n            localStorage.setItem('mcp_token', $('mcp-token')?.value.trim() || '');\n            localStorage.setItem('mcp_allow_read', $('mcp-allow-read-switch')?.checked ? 'true' : 'false');\n            localStorage.setItem('mcp_allow_write', $('mcp-allow-write-switch')?.checked ? 'true' : 'false');\n            window.dispatchEvent(new CustomEvent('mcp-config-changed'));\n            \n            const select = $('api-preset-select');"""
if save_mem not in js:
    raise SystemExit('Could not locate memory API save block')
js = js.replace(save_mem, save_mcp, 1)
main.write_text(js, encoding='utf-8')

client = r'''(() => {
'use strict';
const PROTOCOL='2025-06-18'; let id=0;
const config=()=>({enabled:localStorage.getItem('mcp_enabled')==='true',url:(localStorage.getItem('mcp_url')||'').trim(),token:(localStorage.getItem('mcp_token')||'').trim(),allowRead:localStorage.getItem('mcp_allow_read')!=='false',allowWrite:localStorage.getItem('mcp_allow_write')==='true'});
const isWriteTool=name=>/(?:^|[_./-])(write|create|update|delete|remove|send|reply|save|set|put|patch|publish|submit|archive|restore)(?:$|[_./-])/i.test(String(name||''));
const parseSse=text=>{const rows=String(text||'').split(/\r?\n/).filter(x=>x.startsWith('data:')).map(x=>x.slice(5).trim()).filter(x=>x&&x!=='[DONE]');if(!rows.length)throw new Error('MCP 服务返回了无法识别的 SSE 响应');return JSON.parse(rows.at(-1));};
async function rpc(method,params={},override={}){const c={...config(),...override};if(!c.url)throw new Error('未配置 MCP 服务地址');const headers={'Content-Type':'application/json','Accept':'application/json, text/event-stream'};if(c.token)headers.Authorization=`Bearer ${c.token}`;if(c.sessionId)headers['Mcp-Session-Id']=c.sessionId;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const res=await fetch(c.url,{method:'POST',headers,body:JSON.stringify({jsonrpc:'2.0',id:++id,method,params}),signal:controller.signal});const sessionId=res.headers.get('Mcp-Session-Id')||res.headers.get('mcp-session-id')||c.sessionId||'';const text=await res.text();if(!res.ok)throw new Error(`HTTP ${res.status}${text?`：${text.slice(0,500)}`:''}`);let payload=null;if(text.trim())payload=(res.headers.get('content-type')||'').includes('text/event-stream')||text.trimStart().startsWith('data:')?parseSse(text):JSON.parse(text);if(payload?.error)throw new Error(payload.error.message||`MCP 错误 ${payload.error.code||''}`.trim());return{result:payload?.result??payload,sessionId};}catch(e){if(e?.name==='AbortError')throw new Error('MCP 请求超过 30 秒，已停止');if(navigator.onLine===false)throw new Error('当前设备已断网');throw e;}finally{clearTimeout(timer);}}
async function initialize(override={}){const first=await rpc('initialize',{protocolVersion:PROTOCOL,capabilities:{},clientInfo:{name:'Jingxu',version:'1.0.0'}},override);try{await rpc('notifications/initialized',{}, {...override,sessionId:first.sessionId});}catch(_){}return first;}
async function listTools(override={}){const init=await initialize(override),listed=await rpc('tools/list',{}, {...override,sessionId:init.sessionId});return{tools:Array.isArray(listed.result?.tools)?listed.result.tools:[],serverInfo:init.result?.serverInfo||null,capabilities:init.result?.capabilities||{},sessionId:listed.sessionId||init.sessionId||''};}
async function callTool(name,args={},override={}){const c={...config(),...override};if(!c.enabled&&!override.ignoreEnabled)throw new Error('MCP 尚未启用');const write=isWriteTool(name);if(write&&!c.allowWrite)throw new Error('当前设置不允许 MCP 写入');if(!write&&!c.allowRead)throw new Error('当前设置不允许 MCP 读取');const init=await initialize(c);return(await rpc('tools/call',{name,arguments:args},{...c,sessionId:init.sessionId})).result;}
async function testConnection({url,token=''}){const r=await listTools({url,token,enabled:true,allowRead:true,allowWrite:false});return{ok:true,toolCount:r.tools.length,tools:r.tools,serverName:r.serverInfo?.name||'',serverVersion:r.serverInfo?.version||''};}
window.MCPClient={getConfig:config,initialize,listTools,callTool,testConnection,isWriteTool};
})();
'''
Path('mcpClient.js').write_text(client, encoding='utf-8')

# The helper files are temporary and should not remain in the feature commit.
Path('tools/apply_mcp_settings.py').unlink(missing_ok=True)
Path('.github/workflows/apply-mcp-settings.yml').unlink(missing_ok=True)
